// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXmuE5eR3A_uD8gCghHNU_5ce2RTlrtvE',
    appId: '1:593039816197:web:4aafc8d125370bfff80e6c',
    messagingSenderId: '593039816197',
    projectId: 'agrisense-01',
    authDomain: 'agrisense-01.firebaseapp.com',
    storageBucket: 'agrisense-01.firebasestorage.app',
    measurementId: 'G-NWCZVLJK5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFB_n1hCjHX3mKTfmXCT1pl9OTTroeDWo',
    appId: '1:593039816197:android:0dad5bd65f4e1291f80e6c',
    messagingSenderId: '593039816197',
    projectId: 'agrisense-01',
    storageBucket: 'agrisense-01.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqdDd3DWJf4FIIZaDg30PLXBtZP_MiUE0',
    appId: '1:593039816197:ios:5438b93ec09dd411f80e6c',
    messagingSenderId: '593039816197',
    projectId: 'agrisense-01',
    storageBucket: 'agrisense-01.firebasestorage.app',
    iosBundleId: 'com.example.agrisense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqdDd3DWJf4FIIZaDg30PLXBtZP_MiUE0',
    appId: '1:593039816197:ios:5438b93ec09dd411f80e6c',
    messagingSenderId: '593039816197',
    projectId: 'agrisense-01',
    storageBucket: 'agrisense-01.firebasestorage.app',
    iosBundleId: 'com.example.agrisense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXmuE5eR3A_uD8gCghHNU_5ce2RTlrtvE',
    appId: '1:593039816197:web:5505199dc213143ef80e6c',
    messagingSenderId: '593039816197',
    projectId: 'agrisense-01',
    authDomain: 'agrisense-01.firebaseapp.com',
    storageBucket: 'agrisense-01.firebasestorage.app',
    measurementId: 'G-JC7S6NQYNV',
  );
}
